/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ee.cybernetica.api;

import ee.cybernetica.model.BusStop;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-04-08T12:57:29.477097300+03:00[Europe/Tallinn]")
@Validated
@Tag(name = "bus-stops", description = "the bus-stops API")
public interface BusStopsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /bus-stops : Create a bus stop
     * Creates a bus stop with given name and location and stores it in the database.
     *
     * @param busStop A new bus stop object with name and coordanites. (optional)
     * @return Returned bus stop object with fullfilled id field from database. (status code 200)
     */
    @Operation(
        operationId = "createBusStop",
        summary = "Create a bus stop",
        tags = { "LineMangagment" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Returned bus stop object with fullfilled id field from database.", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  BusStop.class)))
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/bus-stops",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BusStop> createBusStop(
        @Parameter(name = "BusStop", description = "A new bus stop object with name and coordanites.", schema = @Schema(description = "")) @Valid @RequestBody(required = false) BusStop busStop
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"latitude\" : \"58.385787\", \"name\" : \"Vene\", \"id\" : 0, \"longitude\" : \"26.726408\" }";
                    //ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    /**
     * GET /bus-stops : Gets all bus stops with given filters.
     * Queries all bus stops with given optional name and limit filters.
     *
     * @param maxResults The numbers of items to return. (optional, default to 20)
     * @param name Optional parameter to filter bus stops by partial name. (optional)
     * @return Returned a list of bus stops which fullfill query params. (status code 200)
     */
    @Operation(
        operationId = "readBusStops",
        summary = "Gets all bus stops with given filters.",
        tags = { "LineMangagment" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Returned a list of bus stops which fullfill query params.", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  BusStop.class)))
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/bus-stops",
        produces = { "application/json" }
    )
    default ResponseEntity<List<BusStop>> readBusStops(
        @Min(1) @Max(50) @Parameter(name = "maxResults", description = "The numbers of items to return.", schema = @Schema(description = "", defaultValue = "20")) @Valid @RequestParam(value = "maxResults", required = false, defaultValue = "20") Integer maxResults,
        @Parameter(name = "name", description = "Optional parameter to filter bus stops by partial name.", schema = @Schema(description = "")) @Valid @RequestParam(value = "name", required = false) String name
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"latitude\" : \"58.385787\", \"name\" : \"Vene\", \"id\" : 0, \"longitude\" : \"26.726408\" }";
                    //ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
